### PR TITLE
React App Created

### PR DESCRIPTION
**Pull request by kartikeya532001**
Created react project and Pushed it.

### CODE REVIEW

**Review by animesh-deka — APPROVED** [review]

**Comment by PHAGUN-JAIN** [comment]
Pushing on backend repo?

**Comment by himanshu06d** [comment]
Yes cause ops People are saying that it will difficult for them to manage 2
repos..

**Comment by PHAGUN-JAIN** [comment]
What is the point of meeting if nothing is implemented discussed in meeting?

**Comment by himanshu06d** [comment]
Fagun right now we only have a repo where there exist
1)one folder to create backend
2) another folder to create frontend ( where frontend team has already
build the initial react app )
3) package.json file

And if you want to manage routs exceptionally we can create another folder
for that part also

And we will also need a folder to manage database if everyone agrees :)

**Comment by himanshu06d** [comment]
Fagun when there will be a point to extraction is needed that is why we are
maintaining everything in a separate way. So will manage...Also it will
help the developer to run unit cases if there will front end also available
just by a single click of fetch upstream

**Review by ayush0418 — APPROVED** [review]

**Review by Himanshu-kumar-gupta — APPROVED** [review]
Basic Frontend is developed.

**Comment by himanshu06d** [comment]
Please send the front end screenshot in group so that we can approve the
same

**Review by ansh8tu — APPROVED** [review]

**Review by AAKASH707 — APPROVED** [review]

**Pull request merged**
